In [1]:
import numpy as np
import pandas as pd

Q1

In [10]:
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr2 = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(arr1.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Q2

In [9]:
i = 0
for i in arr1:
    if arr1[i] % 2 != 0:
        arr1[i] = -1
    i = i + 1

print(arr1)

[ 0 -1  2 -1  4 -1  6 -1  8]


Q3

In [15]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(np.where(x > y))
print(np.where(x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


Q4

In [40]:
assign_4 = np.arange(100).reshape(5,-1)

print("The extracted array:")
print(assign_4[:,:4])

The extracted array:
[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


Additional Q1

In [19]:
adq1 = np.random.randint(30, 41, size = (10))

print(adq1)

[35 36 34 35 40 38 32 30 39 31]


Additional Q2.(i)

In [28]:
a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

b = [[7, 8, 10],
     [4, 5, 6],
     [1, 2, 3]]

c = np.add(a, b)
e = np.subtract(a, b)

print(c)
print(e)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 12]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  6]]


Additional Q2.(ii)

In [25]:
print(np.sum(a))
print(np.sum(b, axis = 0))
print(np.sum(c, axis = 1))

45
[12 15 19]
[31 30 30]


Additional Q2.(iii)

In [29]:
d = np.dot(a, b)
print(d)

[[ 18  24  31]
 [ 54  69  88]
 [ 90 114 145]]


Additional Q2.(iv)

In [39]:
print(np.reshape(np.sort(np.reshape(c))))

print(e)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 12]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  6]]


Additional Q2.(v)

In [38]:
print(np.transpose(e))

[[-6  0  6]
 [-6  0  6]
 [-7  0  6]]


Reading CSV file

In [55]:
import csv
import pandas as pd

In [43]:
with open('sample.csv') as f:
    data = csv.reader(f)
    for row in data:
        print(row)

['Programming language', ' Designed by', ' Appeared', ' Extension']
['Python', ' Guido van Rossum', ' 1991', ' .py']
['Java', ' James Gosling', ' 1995', ' .java']
['C++', ' Bjarne Stroustrup', ' 1983', ' .cpp']


Reading a CSV file as Dictionary

In [45]:
reader = csv.DictReader(open('sample.csv'))
for raw in reader:
    print(raw)

OrderedDict([('Programming language', 'Python'), (' Designed by', ' Guido van Rossum'), (' Appeared', ' 1991'), (' Extension', ' .py')])
OrderedDict([('Programming language', 'Java'), (' Designed by', ' James Gosling'), (' Appeared', ' 1995'), (' Extension', ' .java')])
OrderedDict([('Programming language', 'C++'), (' Designed by', ' Bjarne Stroustrup'), (' Appeared', ' 1983'), (' Extension', ' .cpp')])


Writing CSV Files

In [54]:
with open('write.csv', 'w') as file:
    writer = csv.writer(file, delimiter=',')
    writer.writerow(['Programming language', 'Designed by', 'Appeared', 'Extension'])
    writer.writerow(['Python', 'Guido Van Rossum', '1991', '.py'])
    writer.writerow(['Java', 'James Gosling', '1995', '.java'])
    writer.writerow(['C++', 'Bjarne Stroupstrup','1985','.cpp'])    

Reading CSV file with pandas 

In [56]:
result = pd.read_csv('sample.csv')
print(result)

  Programming language         Designed by   Appeared  Extension
0               Python    Guido van Rossum       1991        .py
1                 Java       James Gosling       1995      .java
2                  C++   Bjarne Stroustrup       1983       .cpp


Writing CSV file using Pandas

In [59]:
C = pd.read_csv('sample.csv')
C.to_csv('new.csv', index= None)